version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
      - image: circleci/mongo:3.6.12
      - image: circleci/redis:5.0.4
    steps:
      - checkout
      - run:
          name: Upgrade Yarn
          command: sudo npm i -g yarn@$(node -p 'require("./package.json").engines.yarn')
      - restore_cache:
          name: Restore Yarn cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          name: Save Yarn Package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run tests
          command: yarn test:ci
      # Don't try building connectors if not in branch master or develop
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker build . -t hull/hull-connectors:$CIRCLE_SHA1
      - run:
          name: Publish to docker
          command: |
            docker push hull/hull-connectors:$CIRCLE_SHA1
  deploy:
    docker:
      - image: hull/dcos-deploy:latest
    steps:
      - run:
          name: Push Docker Image & Deploy to Marathon
          command: |
            DOCKER_IMAGE=hull/hull-connectors:$CIRCLE_SHA1
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              APP_ENV="production"
            else
              APP_ENV="staging"
            fi

            ci-login-to-dcos $DCOS_CLUSTER_URL
            marathon-deploy-group /$APP_ENV/connectors $DOCKER_IMAGE
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
                - develop
                - feature/docker-single
          requires:
            - build
