version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
#      - image: circleci/mongo:3.6.12
#      - image: circleci/redis:5.0.4
    steps:
      - checkout
      - run:
          name: Last successfull commit
          command: |
            LAST_SUCCESSFUL_COMMIT=$(curl -Ss -u "$CIRCLE_TOKEN:" "https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME?filter=completed&limit=1" | jq -r '.[0]["vcs_revision"]')
            echo "comparing commits $LAST_SUCCESSFUL_COMMIT and $CIRCLE_SHA1"
            for fn in `cat connectors.txt`; do
                if [ -z `git diff $LAST_SUCCESSFUL_COMMIT $CIRCLE_SHA1 $fn 2>&1`]; then
                  echo "no changes for $fn"
                else
                  echo "changes detected for $fn"
                fi
            done
#      - run:
#          name: Upgrade Yarn
#          command: sudo npm i -g yarn@$(node -p 'require("./package.json").engines.yarn')
#      - restore_cache:
#          name: Restore Yarn cache
#          keys:
#            - yarn-packages-{{ checksum "yarn.lock" }}
#      - run:
#          name: Install Dependencies
#          command: yarn
#      - save_cache:
#          name: Save Yarn Package cache
#          key: yarn-packages-{{ checksum "yarn.lock" }}
#          paths:
#            - ~/.cache/yarn
#      - run:
#          name: Run tests
#          command: yarn test:ci
      # - setup_remote_docker
      # - run:
      #     name: Deploy all connectors
      #     command: |
      #       echo $DEPLOYMENT_CONFIG_JS | base64 -d > deployment.config.js
      #       CONNECTORS=`BRANCH=$CIRCLE_BRANCH sh scripts/get-connectors-to-deploy.sh`
      #       docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
      #       echo $CONNECTORS
      #       echo "$CONNECTORS" | while IFS= read -r C ; do CONNECTOR=$C BRANCH=$CIRCLE_BRANCH sh scripts/deploy-to-heroku.sh; done
